# Generated by Django 5.1.6 on 2025-06-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annuaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annuaire_id', models.IntegerField()),
                ('nom', models.CharField(max_length=50)),
                ('mobile_1', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_2', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_3', models.CharField(blank=True, max_length=20, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Enter a valid email address.', max_length=254, unique=True, verbose_name='Email address')),
            ],
        ),
    ]
