# Generated by Django 5.1.6 on 2025-06-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_id', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/fac')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('adresse', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
