# Generated by Django 5.1.6 on 2025-07-08 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/fac')),
                ('intitule_poste', models.CharField(max_length=100)),
                ('prerequis_recrutement', models.CharField(blank=True, max_length=1000, null=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('faculte_rattachement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='Faculties.faculty')),
            ],
        ),
    ]
