# Generated by Django 5.1.6 on 2025-07-08 20:05

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Faculties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement_id', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/departement')),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.CharField(max_length=1000)),
                ('formation_dispo', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M', 'Master'), ('L', 'Licence'), ('LP', 'Licence Pro'), ('SC', 'Système classique')], default=['M', 'L', 'LP', 'SC'], max_length=9)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='Faculties.faculty')),
            ],
        ),
    ]
