# Generated by Django 5.1.6 on 2025-06-21 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
        ('Faculties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='Faculties.faculty'),
        ),
    ]
