# Generated by Django 5.1.6 on 2025-08-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departement',
            name='formation_dispo',
        ),
    ]
