# Generated by Django 5.1.6 on 2025-06-28 15:00

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='formation_dispo',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M', 'Master'), ('L', 'Licence'), ('LP', 'Licence Pro'), ('SC', 'Système classique')], default=['M', 'L', 'LP', 'SC'], max_length=9),
        ),
    ]
