# Generated by Django 5.1.6 on 2025-07-08 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('formation_id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('credits', models.PositiveIntegerField()),
                ('duree', models.CharField(max_length=100)),
                ('niveau_etude', models.CharField(max_length=100)),
                ('langue_enseignement', models.CharField(max_length=100)),
                ('capitalisation', models.TextField()),
                ('progression', models.TextField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='Departments.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_volume', models.FloatField(help_text='Volume horaire (heures/crédits)')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Formations.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='Formations.formation')),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='Formations.speciality'),
        ),
    ]
